services:
  # Web service (Node.js)
  - type: web
    name: fair-money-bot
    env: node
    plan: free
    region: singapore # Change this to your preferred region
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    healthCheckTimeout: 5000
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fair-money-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false # This should be manually set in the Render dashboard

databases:
  # PostgreSQL database
  - name: fair-money-db
    plan: free
    region: singapore # Change this to your preferred region
    postgresMajorVersion: 14